CREATE TABLE AUTH
(
    USERNAME VARCHAR2(30) NOT NULL
        CONSTRAINT FK_MEMBER_AUTH FOREIGN KEY REFERENCES MEMBER,
    AUTHORITY     VARCHAR2(30) DEFAULT 'ROLE_USER' NOT NULL
);

CREATE UNIQUE INDEX IX_AUTH_USERNAME ON AUTH (USERNAME, AUTHORITY);