CREATE TABLE MEMBER
(
    USERNAME    VARCHAR2(50)         NOT NULL
        CONSTRAINT MEMBER_PK
        PRIMARY KEY,
    PASSWORD    CHAR(60)             NOT NULL,
    ENABLED     CHAR DEFAULT 1       NOT NULL,
    AUTHORITIES VARCHAR2(50)         NOT NULL,
    REGDATE     DATE DEFAULT SYSDATE NOT NULL
);
