CREATE TABLE MEMBER
(
    USERNAME  VARCHAR2(30) NOT NULL
        CONSTRAINT MEMBER_PK PRIMARY KEY,
    PASSWORD  CHAR(60)                NOT NULL,
    ENABLED   CHAR(1) DEFAULT '1'     NOT NULL,
    MOBILE    VARCHAR2(13) NOT NULL,
    EMAIL     VARCHAR2(50) NOT NULL,
    GENDER    CHAR(1)                 NOT NULL,
    BIRTHDATE VARCHAR2(14) NOT NULL,
    REGDATE   DATE    DEFAULT SYSDATE NOT NULL
);
