CREATE TABLE MEMBERIMG
(
    USERNAME VARCHAR2(30) NOT NULL
        CONSTRAINT MEMBERIMG_PK PRIMARY KEY
        ON DELETE CASCADE,
    ABSPATH  VARCHAR2(300) NULL,
    RELPATH  VARCHAR2(300) NULL,
    FILENAME VARCHAR2(300) NULL
);

ALTER TABLE MEMBERIMG
    ADD CONSTRAINT MEMBERIMG_MEMBER_FK FOREIGN KEY (USERNAME) REFERENCES MEMBER (USERNAME);
